export const APPCONF = 'appConf'
export const NOTICENUM = 'noticeNum'
export const DICTIONARY = 'dictionary'
export const USERINFO = 'userinfo'
export const BEFORELOGIN = 'beforeLogin'
export const TOPMENU = 'topMenu'
export const SIDEMENU = 'sideMenu'
export const PERMISSION = 'permission'
